// app/layout.jsx

import Link from "next/link";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  

  return (
    <html lang="en">
      <body>
        {children} {/* This will render the page content inside the layout */}
      </body>
    </html>
  );
}
