import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const style = {
    backgroundColor: "blue ",
    color: "white",
    fontSize: "0.8rem",
    padding: 10,
    cursor: "pointer",
    border: "none",
    borderRadius: "9px",
  };
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="link">
          <Link href="/assignment-1">
            <button style={style}>Assignment Day 1</button>
          </Link>
          <Link href="/assignment-2">
            <button style={style}>Assignment Day 2</button>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
